### ISSUE TITLE
TreeMapViewer.html not displaying TreeMap

### ISSUE THREAD

**Issue by nish2292** [inf295uci-2015/SeeSoftOnD3#7] opened 2015-05-18 22:46 UTC
TreeMapViewer.html not displaying TreeMap upon clicking update, as reported by @nish2292 on slack: "Nothing happens when I click update. It shows nothing. Empty page."

**Comment by VijayKrishna** [comment] 2015-05-18 22:47
"Not working" simply means to me that nothing happens when you open that page. Is that really the case? Or does something not work based on a detailed expectation that you have??

**Comment by VijayKrishna** [comment] 2015-05-18 22:48
also, what repository are you trying to visualize when you get this issue?

**Comment by nish2292** [comment] 2015-05-18 22:49
None of the repos work.

**Comment by VijayKrishna** [comment] 2015-05-18 22:49
what repositories have you tried?

**Comment by nish2292** [comment] 2015-05-18 22:53
None of my own repos or any of the repos of inf295uci-2015.

**Comment by maxcn** [comment] 2015-05-18 22:54
![screen shot 2015-05-18 at 3 53 17 pm](https://cloud.githubusercontent.com/assets/5082829/7692195/17556a1a-fd76-11e4-8e44-535bbee33a18.png)

this is what I tried. Does this mean it is working?

**Comment by VijayKrishna** [comment] 2015-05-18 22:56
@maxcn yes that means it is working, can you tell me what repository you are trying to visualize?
@nish2292 and @maxcn: can everyone also report the exact branches that you are using while working with this issue?

**Comment by nish2292** [comment] 2015-05-18 22:57
I was working on the master branch.

**Comment by maxcn** [comment] 2015-05-18 22:57
This is the mockito repo I tried before and it is the master branch. I am still working on the new Guava repo.

**Comment by VijayKrishna** [comment] 2015-05-18 23:01
Oh, and what browsers are you guys using. So, i am using Firefox, I am trying to visualize the `SourceSurfer` repository and I just pulled the latest master branch of `SeeSoftOnD3` while working on this issue. And I am able to reproduce @nish2292's issue on my end.

Moreover, this is the exact error that i am getting when i hit update: 
> ReferenceError: offline is not defined ... d3-seesoft.js:79:0

**Comment by nish2292** [comment] 2015-05-18 23:10
I'm using chrome.

**Comment by maxcn** [comment] 2015-05-18 23:13
I think chrome is ok because I'm using it.

**Comment by VijayKrishna** [comment] 2015-05-18 23:13
@nish2292 please check a pull request ( #8 ) that i just assigned to you.

**Comment by VijayKrishna** [comment] 2015-05-18 23:16
@maxcn can you confirm which branch and commit of `SeesoftOnD3` are you using to report your findings for this issue? Can you also confirm the browser that you are using? Thanks a bunch!

**Closed** 2015-05-18 23:37 UTC
Labels: bug
